spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/erupt_test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: panda
    password: 123456
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
  profiles:
    active: dev
  mail:
    username: tank_panda@qq.com
    password: hhd12091209
    host: smtp.qq.com
    properties:
      mail.smtp.ssl.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.required: true