
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/idiom_sequence?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE
    password: 123456
    username: panda
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      static-locations: classpath:/web/

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
